title: Internationalist Communist Library
description: Official shared theoretical library of the internationalist communist tradition

baseurl: "/IntComLibrary"
url: "https://intcomden.github.io"

collections:
  texts:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - .gitignore
  - .nojekyll
  - scripts
